StateManagement/StateManagement/Models/ErrorViewModel.cs
namespace StateManagement.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

StateManagement/StateManagement/Models/Temp.cs
namespace StateManagement.Models
{
    public class Temp
    {
        public int userID { get; set; }
    }
}

StateManagement/StateManagement/Models/User.cs
namespace StateManagement.Models
{
    public class User
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
    }
}

StateManagement/StateManagement/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using StateManagement.Models;
using System.Diagnostics;

namespace StateManagement.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

StateManagement/StateManagement/Controllers/TempDataController.cs
using Microsoft.AspNetCore.Mvc;

namespace StateManagement.Controllers
{
    public class TempDataController : Controller
    {
        public IActionResult First()
        {
            TempData["UserID"] = 101;
            return View();
        }
        public IActionResult Second()
        {
            var userID = TempData["UserId"] ?? null;
            return View();
        }
        public IActionResult Third()
        {
            var userID = TempData["UserId"] ?? null;
            return View();
        }
    }
}

StateManagement/StateManagement/Controllers/WelcomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Net.Cache;
using StateManagement.Models;

namespace StateManagement.Controllers
{
	public class WelcomeController : Controller
	{
		private readonly IHttpContextAccessor _contextAccessor;

		public WelcomeController(IHttpContextAccessor contextAccessor)
		{
			_contextAccessor = contextAccessor;
		}
		
		public IActionResult Index()
		{
			//adding a simple cookie using HttpContextAccessor
			var cookieOptions = new CookieOptions
			{
				Expires = DateTimeOffset.UtcNow.AddDays(1)
			};
			_contextAccessor.HttpContext.Response.Cookies.Append("MyCookie", "My Cookie Value", cookieOptions);

			HttpContext.Session.SetInt32("Id", 100);
			HttpContext.Session.SetString("Name", "John");
			HttpContext.Session.SetInt32("Age", 32);
			return View();
		}
		public IActionResult Get()
		{
			//to read the cookie
			string myCookieValue = _contextAccessor.HttpContext.Request.Cookies["MyCookie"];
			TempData["Cookies"] = myCookieValue;

			User u = new User()
			{
				Id = HttpContext.Session.GetInt32("Id").Value,
				Name = HttpContext.Session.GetString("Name"),
				Age = HttpContext.Session.GetInt32("Age").Value
			};
			return View(u);

		}

		[HttpGet]
		public IActionResult SetHiddenValue()
		{
			User newUser = new User()
			{
				Id = 101,
				Name = "Biplav",
				Age = 22
			};
			return View(newUser);
		}

		[HttpPost]
		public IActionResult SetHiddenValue(IFormCollection keyValues) {
			var id = keyValues["Id"];
			return View();
		}
	}
}

StateManagement/StateManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StateManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StateManagement.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">StateManagement</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - StateManagement - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

StateManagement/StateManagement/Views/TempData/First.cshtml
@model StateManagement.Models.Temp

@{
    ViewData["Title"] = "First";
    //var userid = TempData["UserID"];
    //TempData.Keep("UserID");
}

<h1>First</h1>

<div>
    <h4>Temp</h4>
    <form asp-controller="TempData" asp-action="First" method="post">
        <input type="submit" value="Set Temp Data">
    </form>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.userID)
        </dt>
        <dd class="col-sm-10">
            @*TempData["UserID"]*@
            @TempData.Peek("UserID")  @*Peek() displays data and retains it for next request only*@
        </dd>
    </dl>
</div>
<p>
    <a asp-controller="TempData" asp-action="Second">Second View Page</a>
</p>

StateManagement/StateManagement/Views/TempData/Second.cshtml
@model StateManagement.Models.Temp

@{
    ViewData["Title"] = "Second";
    //TempData.Keep();     //retains the value corresponding to the key passed in TempData
}

<h1>Second</h1>

<div>
    <h4>Temp</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.userID)
        </dt>
        <dd class="col-sm-10">
            @TempData["UserID"]
            @*TempData.Peek("UserID");*@
        </dd>
    </dl>
</div>
<p>
    <a asp-controller="TempData" asp-action="Third">Third View Page</a>
</p>

StateManagement/StateManagement/Views/TempData/Third.cshtml
@model StateManagement.Models.Temp

@{
    ViewData["Title"] = "Third";
}

<h1>Third</h1>

<div>
    <h4>Temp</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.userID)
        </dt>
        <dd class="col-sm-10">
            @TempData["UserID"]
        </dd>
    </dl>
</div>
<p>
    <a asp-controller="TempData" asp-action="First">First View Page</a>
</p>